name: Cross-Compile FFMPEG, ffprobe, and ffplay for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ffmpeg:
    name: Cross-Compile FFMPEG, ffprobe, and ffplay for Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Get Latest Release Version
        id: get_version
        run: |
          # Ensure you are getting the latest commit hash of the release/7.1 branch
          repo_version=$(git ls-remote https://github.com/FFmpeg/FFmpeg.git refs/heads/release/7.1 | awk '{print $1}')
          echo "Latest FFmpeg commit hash for release/7.1: $repo_version"
          echo "repo_version=$repo_version" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      
      - name: Install MinGW-w64 and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-mingw-w64-x86-64 \
            g++-mingw-w64-x86-64 \
            make \
            yasm \
            nasm \
            pkg-config \
            zlib1g-dev \
            libtool \
            autoconf \
            automake \
            cmake \
            wget \
            git

      - name: Set up Build Environment
        run: |
          git fetch origin release/7.1
          git checkout release/7.1

      - name: Run FFMPEG Build Script
        run: |
          chmod +x build-ffmpeg.sh
          ./build-ffmpeg.sh --build --enable-gpl-and-non-free --latest
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Compiled Binaries
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-binaries-windows-x64
          path: |
            ./bin/ffmpeg.exe
            ./bin/ffprobe.exe 
            ./bin/ffplay.exe
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
