name: Cross-Compile FFMPEG, ffprobe, and ffplay for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ffmpeg:
    name: Cross-Compile FFMPEG, ffprobe, and ffplay for Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          export TERM=xterm
          xargs sudo apt-get -y install < packages.txt
          sudo apt-get update
          sudo apt-get full-upgrade
          sudo apt-get install -y \
            gcc-mingw-w64-x86-64 \
            g++-mingw-w64-x86-64 \
            make \
            yasm \
            nasm \
            meson \
            ninja-build \
            pkg-config \
            gcc \
            g++ \
            zlib1g-dev \
            libtool \
            autoconf \
            automake \
            cmake \
            wget \
            git
          chmod +x build-ffmpeg.sh
          bash build-ffmpeg.sh --build --enable-gpl-and-non-free --latest --compiler=gcc
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Compiled Binaries
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-binaries-windows-x64
          path: |
            ./bin/ffmpeg.exe
            ./bin/ffprobe.exe 
            ./bin/ffplay.exe
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
