name: Cross-Compile FFmpeg

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ffmpeg:
    name: Cross-Compile FFMPEG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          export TERM=xterm
          sudo apt-get update
          xargs sudo apt-get -y install < packages.txt
          
          sudo apt-get install -y \
            ragel cvs yasm pax nasm gperf autogen autoconf-archive \
            libsamplerate-dev \
            qtbase5-dev \
            libsndfile1-dev \
            gcc-mingw-w64-x86-64 \
            g++-mingw-w64-x86-64 \
            make \
            meson \
            ninja-build \
            pkg-config \
            gcc \
            g++ \
            zlib1g-dev \
            libtool \
            autoconf \
            automake \
            cmake \
            wget \
            git
          sudo -H pip3 -qq install meson ninja

      - name: Run Build Script
        run: |
          chmod +x build-ffmpeg.sh
          bash ./build-ffmpeg.sh --build --compiler=gcc --latest --enable-gpl-and-non-free -j 4
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Compiled Binaries
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-binaries-windows-x64
          path: |
            ./bin/ffmpeg.exe
            ./bin/ffprobe.exe
            ./bin/ffplay.exe
