name: Cross-Compile FFMPEG, ffprobe, and ffplay for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ffmpeg:
    name: Cross-Compile FFMPEG, ffprobe, and ffplay for Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Get Latest Release Version
        id: get_version
        run: |
          repo_version=$(git ls-remote --tags https://github.com/FFmpeg/FFmpeg.git | grep "n7.1" | awk -F'/' '{print $3}' | sort -V | tail -n 1)
          echo "Latest FFmpeg release version: $repo_version"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-mingw-w64-x86-64 \
            g++-mingw-w64-x86-64 \
            make \
            yasm \
            nasm \
            meson \
            ninja-build \
            pkg-config \
            gcc \
            g++ \
            zlib1g-dev \
            libtool \
            autoconf \
            automake \
            cmake \
            wget \
            git

      - name: Run FFMPEG Build Script
        run: |
          chmod +x build-ffmpeg.sh
          ./build-ffmpeg.sh --build --enable-gpl-and-non-free --latest
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Compiled Binaries
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-binaries-windows-x64
          path: |
            ./bin/ffmpeg.exe
            ./bin/ffprobe.exe 
            ./bin/ffplay.exe
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
