name: Build FFmpeg with Meson and Ninja

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0

      # Cache system dependencies
      - name: Cache System Dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/mingw-w64
          key: ${{ runner.os }}-mingw-w64-${{ hashFiles('**/build-ffmpeg.sh') }}
          restore-keys: |
            ${{ runner.os }}-mingw-w64-

      # Install required dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential yasm pkg-config git \
            mingw-w64 cmake nasm python3 python3-pip ninja-build meson \
    
      # Set up MinGW environment for cross-compilation
      - name: Set up MinGW for Windows Cross-Compilation
        run: |
          export PATH=/usr/x86_64-w64-mingw32/bin:$PATH
          export CROSS_PREFIX=x86_64-w64-mingw32-
          echo "MinGW cross-compiler setup completed"

      # Run FFmpeg Build Scripta)
      - name: Run FFmpeg Build Script
        run: |
          export TERM=xterm
          bash ./build-ffmpeg.sh --build --enable-gpl-and-non-free --compiler=gcc

      # Store the build artifacts (Windows executables)
      - name: Upload Windows Executables
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-windows-executables
          path: ffmpeg-build-script/ffmpeg*/ffmpeg.exe
